import { z } from 'zod';
import { DomainError } from './errors.js';
import {
  actorSchema,
  timestampSchema,
  type Actor,
  type EntityType,
  type Timestamp,
} from './primitives.js';
import type { StateMachine } from './state-machine.js';

/** Metadata of entities that change over time (optimistic locking via `version`, PHASE 02). */
export const mutableMetaShape = {
  createdAt: timestampSchema,
  createdBy: actorSchema,
  updatedAt: timestampSchema,
  version: z.int().min(1),
};

/** Metadata of append-only records: corrections are new records (§2.2). */
export const immutableMetaShape = {
  createdAt: timestampSchema,
  createdBy: actorSchema,
};

/** Who acts and when. Time is passed in explicitly: domain functions never read the clock. */
export interface DomainContext {
  readonly actor: Actor;
  readonly at: Timestamp;
}

export interface CreateContext<Id> extends DomainContext {
  /** Generated by the caller, normally with `uuidv7()` from `@roi-dealer/shared`. */
  readonly id: Id;
}

export function mutableMeta(context: DomainContext) {
  return {
    createdAt: context.at,
    createdBy: context.actor,
    updatedAt: context.at,
    version: 1,
  };
}

export function immutableMeta(context: DomainContext) {
  return { createdAt: context.at, createdBy: context.actor };
}

/** Validates a complete entity; schema failures become `DomainError('invariant_violation')`. */
export function parseEntity<T>(schema: z.ZodType<T>, entity: EntityType, value: unknown): T {
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new DomainError('invariant_violation', `Invalid ${entity}`, {
      entity,
      issues: result.error.issues.map((issue) => ({
        path: issue.path.map(String).join('.'),
        message: issue.message,
      })),
    });
  }
  return result.data;
}

/** Human gate: only the owner may take this action (constitution §2.3, §2.7). */
export function assertOwner(actor: Actor, action: string): void {
  if (actor.type !== 'owner') {
    throw new DomainError('owner_required', `Only the owner may ${action}`, {
      action,
      actor_type: actor.type,
    });
  }
}

interface Versioned<S extends string> {
  readonly status: S;
  readonly updatedAt: Timestamp;
  readonly version: number;
}

/**
 * Moves an entity along its lifecycle and returns a new, re-validated version.
 * Never mutates the input.
 */
export function transition<S extends string, T extends Versioned<S>>(
  entity: T,
  machine: StateMachine<S>,
  schema: z.ZodType<T>,
  to: S,
  context: DomainContext,
  patch: Partial<T> = {},
): T {
  machine.assertTransition(entity.status, to);
  return parseEntity(schema, machine.entity, {
    ...entity,
    ...patch,
    status: to,
    updatedAt: context.at,
    version: entity.version + 1,
  });
}
